### ISSUE TITLE
Package size is too large to publish to pub.dev

### ISSUE THREAD

**Issue by BitcoinZavior** [LtbLightning/bdk-flutter#117]
After adding macOS support, package size is too large to publish to pub.dev.

publish is failing with:

`Uncompressed package archive is too large (size > 104857600).`

Need to consider options for publishing package without binaries and have binaries downloaded on package installation.

**Comment by ethicnology** [comment]
Hey there, is this still an issue ?

If no, is it possible to draft a new pub.dev release, since importing `bdk_flutter` using git in another package throws warning

```yaml
  bdk_flutter:
    git:
      url: https://github.com/LtbLightning/bdk-flutter
      ref: main
```

```sh
Publishable packages can't have 'git' dependencies.
Try adding a 'publish_to: none' entry to mark the package as not for publishing or remove the git dependency.
```
