### ISSUE TITLE
flutter_rust_bridge version incompatibility

### ISSUE THREAD

**Issue by ethicnology** [LtbLightning/bdk-flutter#150]
Hey there,

I would like to ask if there is any reason to restrict `flutter_rust_bridge` between `>=2.0.0` and `<2.1.0` instead of `^2.0.0` or `^2.1.0` ?

This create incompatibility with packages that rely on more updated versions of `flutter_rust_bridge`, currently `^2.6.0`

Example:
```sh
flutter pub add bip85

Because every version of bip85 depends on flutter_rust_bridge ^2.6.0 and every version of bdk_flutter
  from git depends on flutter_rust_bridge >=2.0.0 <2.1.0, bip85 is incompatible with bdk_flutter from
  git.
```

**Comment by Hamaad-coder** [comment]
Simple remove version from flutter_rust_bridge: ^version to  flutter_rust_bridge: empty in pubspec.yaml file. It will automatically pick version.

**Comment by ice-tychon** [comment]
@Hamaad-coder It doesn't help, in runtime I get:
```
flutter_rust_bridge's codegen version (2.0.0) should be the same as runtime version (2.7.0)
```

**Comment by ice-tychon** [comment]
I created a PR to solve the issue: https://github.com/LtbLightning/bdk-flutter/pull/158

In a meanwhile you can use my branch in `pubspec.yaml`:
``` 
  bdk_flutter:
    git:
        url: https://github.com/ice-tychon/bdk-flutter.git
        ref: chore/update-flutter-rust-bridge
```
