### ISSUE TITLE
`DescriptorPublicKey.fromString()` accepts `xpub` but not `ypub` or `zpub`

### ISSUE THREAD

**Issue by ethicnology** [LtbLightning/bdk-flutter#175]
During unit testing of `PkOrF.xOnlyPubkey` / `PkOrF.pubkey` and `DescriptorPublicKey`, I encountered an unexpected behavior: `DescriptorPublicKey.fromString()` accepts an `xpub` but fails when given a `ypub`, `zpub` or even an external descriptor that contains an xpub 

```dart
// Descriptor
const externalDescriptor =
    'wpkh([182551a3/84h/0h/0h]xpub6DM9LRnPTBFRREps8bsNhfGKZ9Phwz6QSWG4iwdxLF2jfMKCncXD7pMyZhjWXmD8QQGPa1ENYZuvV8shstsZmfpZKAXinpoweXCuNBMc5uz/0/*)';

// Extended Public Keys
const xpub =
    'xpub6ExMPLvz3jqYHu2XzgjEFVgCd5K3HP8kMworksijDYCHAQKH1GK49iYuha6gPvtKo3i4U3rDAzzQL6Er5AgVrKnYyAxytRHhB82UNzvTEtK';
const ypub =
    'ypub6Zvt7zyscLqKLxxBm43Wm4wf3XHG9FKRPYgwK5Jcymrup8qhg39wDNvRnDFLwNEXKVcpLJK6KTLQ2LdR8iwnCvSGHTKQs7ooL79FyDekNaa';
const zpub =
    'zpub6t1F1TKqVvFXuWEb8A3z4ifT6FaPzpstcV6D4tyZkCXMtg7NaETqFe9agijNW8bpy2qQYCRmDm9hUmWuyAc6FqHsofHY5TiqiTsJBr2d9uM';


group('test bdk DescriptorPublicKey', () {
  test('Why does this work for an xpub but not for a ypub / zpub?', () async {
    expect(() async {
      await bdk.DescriptorPublicKey.fromString(xpub);
    }, returnsNormally); 
  });


  test('external descriptor', () async {
    expect(() async {
      await bdk.DescriptorPublicKey.fromString(externalDescriptor);
    }, throwsA(anything));
  });

  test('ypub', () async {
    expect(
      () async => await bdk.DescriptorPublicKey.fromString(ypub),
      throwsA(anything),
    );
  });

  test('zpub', () async {
    expect(
      () async => await bdk.DescriptorPublicKey.fromString(zpub),
      throwsA(anything),
    );
  });
});

```

Environment 

```yaml
bdk_flutter:
    git:
      url: https://github.com/LtbLightning/bdk-flutter
      ref: main
```

```
bdk_flutter:
    dependency: "direct main"
    description:
      path: "."
      ref: main
      resolved-ref: ac8d102240a4242e319e71492d3698828177e97b
      url: "https://github.com/LtbLightning/bdk-flutter"
    source: git
    version: "0.31.3"
```
